---
title: "Pauta para el trabajo personal de fin de curso"
subtitle: 'Diplomado en Análisis de Datos con R e Investigación reproducible para Biociencias.'
author:
 name: Dr. José A. Gallardo y Dra. María Angélica Rueda.
 affiliation: Pontificia Universidad Católica de Valparaíso
 email: <jose.gallardo@pucv.cl>
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
  word_document: default
  pdf_document:
    latex_engine: xelatex
---

<style>
#TOC {
  color: black;
  font-familiy: Calibri;
  font-size: 14px;
  border-color: #708090; 
}
body {
   color: black;
   font-familiy: Calibri;
}

pre {
  color: black;
  background-color: #F8F8FF;
}
# header {
  color: #800000;
  font-familiy: Calibri;
  background-color: #F5F5F5;
  opacity: 0.8;
  font-size: 16px;
}
</style>

## INSTRUCCIONES GENERALES

**1)** Entregar un reporte del trabajo personal de fin de curso en formato html + presentación resumen en formato Beamer desarrollado con Rmarkdwon. Envíe el reporte al siguiente correo <genomica.aplicada@pucv.cl> antes de las  **23:59 PM del martes 06 de diciembre**.  

**2)** Trabajos no entregadas o entregadas fuera de plazo se califican con la nota mínima 1,0.

```{r setup, include=FALSE, warning=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## DESCRIPCIÓN Y CONTENIDO DEL TRABAJO

El **trabajo** corresponde a un proyecto personal de análisis de datos de biociencias con R.

El trabajo se puede realizar con los mismos datos del análisis exploratorio o con otros si lo estima conveniente.

El trabajo estará compuesto por

**1) Proyecto Git Hub:** Control de versiones del trabajo realizado, cada día de trabajo debe quedar registrado en el proyecto git. Incluye archivo **Readme**:

**2) Proyecto Posit.cloud:** Incluye datos que fueron analizados en formato .xls o similar y códigos utilizados para el análisis exploratorio de datos en formato .R y/o .Rmd.

**3) Reporte html:** Análisis de datos en formato html.

## EVALUACIÓN DEL TRABAJO

**Parámetros para el cálculo de la nota.**

|  **Item** | **valor**      |
|:-------------|:------------------|
| **Nota máxima** | 7,0 |
| **Nota mínima** | 1,0 |
| **Nota aprobación** | 4,0 |
| **Exigencia para aprobar** | 60% |
| **Puntaje máximo** | 40 |

**Puntaje según nivel de logro alcanzado en cada componente evaluado.**

|  **Nivel de logro** | **Puntaje**      |
|:-------------|:------------------|
| **Excelente** | 4 |
| **Muy bueno** | 3 |
| **Bueno** | 2 |
| **Suficiente** | 1 |
| **Insuficiente** | 0 |

**Puntaje para cada item a evaluar**  

**Proyecto Git Hub**  

**1.-** Evidencias del uso de control de versiones en github **(4 puntos)**.    
**2.-** Archivo README en github **(4 puntos)**: Incluye título del trabajo, autor, un párrafo con la descripción del problema a resolver, uno con el resumen de los métodos estadísticos aplicados, la hipótesis que se puso a prueba y la conclusión principal del trabajo.

**Proyecto Posit.cloud y reporte html**  
**3.-** Describe la variación de las variables de estudio usando histogramas **(4 puntos)**.  
**4.-** Identifica si los datos están balanceados o no entre tratamientos usando tablas de frecuencia **(4 puntos)**.  
**5.-** Establece relación entre variables cuantitativas y factores usando gráficas de correlación, boxplot, interacción o de tamaño de los efectos **(4 puntos)**.  
**6.-** Identifica si existen errores, datos faltantes o valores atípicos **(4 puntos)**.  
**7.-** Resume los datos usando tablas y estadística descriptiva **(4 puntos)**.  
**8.-** Utiliza librerías **readxl**, **dplyr**, **ggplot2** para el análisis exploratorio de datos **(4 puntos)**.  
**9.-** Propone hipótesis y realiza análisis estadístico de los datos, incluye evaluación de supuestos si corresponde.**(4 puntos)**.  
**10.-**Presenta, interpreta resultados y realiza conclusión.**(4 puntos)**.